<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-WorkerUCABService-4e4d9cc2-6f6c-4d75-9f51-fb3dfd860b2d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Procesos\Plantillas\Logs\**" />
    <Content Remove="Procesos\Plantillas\Logs\**" />
    <EmbeddedResource Remove="Procesos\Plantillas\Logs\**" />
    <None Remove="Procesos\Plantillas\Logs\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="itext7" Version="8.0.4" />
    <PackageReference Include="itext7.bouncy-castle-adapter" Version="8.0.4" />
    <PackageReference Include="iTextSharp" Version="5.5.13.3" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="8.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NuGet.Protocol" Version="6.10.0" />
    <PackageReference Include="RestSharp" Version="111.0.0" />
    <PackageReference Include="Serilog" Version="4.0.1" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Docs\Correo\" />
    <Folder Include="Procesos\Plantillas\Logss\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Procesos\plantillaCorreo.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
